# Food Delivery Operations Analytics

## Project Objective

This project analyzes food delivery operations to identify the factors that influence delivery time and cause delays.

The analysis will investigate the relationship between delivery time and factors such as:

- Weather conditions
- Road traffic density
- Distance
- Vehicle type and condition
- Delivery partner rating and age
- Multiple deliveries
- City type
- Festivals and other operational factors

## Business Question

> What factors are causing food deliveries to take longer, and where should the company take action to reduce delivery delays?

## Project Workflow

1. Data Understanding & Cleaning
2. Exploratory Data Analysis
3. SQL Analysis
4. Statistical Analysis
5. Advanced Analysis
6. Power BI Dashboard
7. Business Recommendations

# 01. Data Understanding & Cleaning

Understand the structure and quality of the food delivery dataset and prepare it for reliable analysis.

### Objectives

- Understand the dataset structure and variables
- Identify missing values and incorrect data types
- Detect invalid or inconsistent values
- Clean and standardize the dataset
- Validate the cleaned data
- Save the final cleaned dataset for downstream analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/raw/train.csv")

In [3]:
df.shape

(45593, 20)

In [4]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [5]:
df.columns.tolist()

['ID',
 'Delivery_person_ID',
 'Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Order_Date',
 'Time_Orderd',
 'Time_Order_picked',
 'Weatherconditions',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City',
 'Time_taken(min)']

In [6]:
df.dtypes

ID                              object
Delivery_person_ID              object
Delivery_person_Age             object
Delivery_person_Ratings         object
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weatherconditions               object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries             object
Festival                        object
City                            object
Time_taken(min)                 object
dtype: object

In [7]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          45593 non-null  object
 3   Delivery_person_Ratings      45593 non-null  object
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  45593 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            45593 non-null  object
 12  Road_traffic_density         45593 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          45593 non-null  object
 17  Festival                     45593 non-null  object
 18  City                         45593 non-null  object
 19  Time_taken(min)              45593 non-null  object
dtypes: float64(4), int64(1), object(15)
memory usage: 7.0+ MB

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["Delivery_person_Age"].unique()

array(['37', '34', '23', '38', '32', '22', '33', '35', '36', '21', '24',
       '29', '25', '31', '27', '26', '20', 'NaN ', '28', '39', '30', '15',
       '50'], dtype=object)

In [11]:
df["Delivery_person_Ratings"].unique()

array(['4.9', '4.5', '4.4', '4.7', '4.6', '4.8', '4.2', '4.3', '4', '4.1',
       '5', '3.5', 'NaN ', '3.8', '3.9', '3.7', '2.6', '2.5', '3.6',
       '3.1', '2.7', '1', '3.2', '3.3', '6', '3.4', '2.8', '2.9', '3'],
      dtype=object)

In [12]:
df["Time_taken(min)"].unique()

array(['(min) 24', '(min) 33', '(min) 26', '(min) 21', '(min) 30',
       '(min) 40', '(min) 32', '(min) 34', '(min) 46', '(min) 23',
       '(min) 20', '(min) 41', '(min) 15', '(min) 36', '(min) 39',
       '(min) 18', '(min) 38', '(min) 47', '(min) 12', '(min) 22',
       '(min) 25', '(min) 35', '(min) 10', '(min) 19', '(min) 11',
       '(min) 28', '(min) 52', '(min) 16', '(min) 27', '(min) 49',
       '(min) 17', '(min) 14', '(min) 37', '(min) 44', '(min) 42',
       '(min) 31', '(min) 13', '(min) 29', '(min) 50', '(min) 43',
       '(min) 48', '(min) 54', '(min) 53', '(min) 45', '(min) 51'],
      dtype=object)

In [13]:
df[[
    "Delivery_person_Age",
    "Delivery_person_Ratings",
    "Time_taken(min)",
    "Order_Date",
    "Time_Orderd",
    "Time_Order_picked"
]].nunique()

Delivery_person_Age         23
Delivery_person_Ratings     29
Time_taken(min)             45
Order_Date                  44
Time_Orderd                177
Time_Order_picked          193
dtype: int64

In [14]:
df[[
    "Order_Date",
    "Time_Orderd",
    "Time_Order_picked"
]].head(10)

   Order_Date Time_Orderd Time_Order_picked
0  19-03-2022    11:30:00          11:45:00
1  25-03-2022    19:45:00          19:50:00
2  19-03-2022    08:30:00          08:45:00
3  05-04-2022    18:00:00          18:10:00
4  26-03-2022    13:30:00          13:45:00
5  11-03-2022    21:20:00          21:30:00
6  04-03-2022    19:15:00          19:30:00
7  14-03-2022    17:25:00          17:30:00
8  20-03-2022    20:55:00          21:05:00
9  12-02-2022    21:55:00          22:10:00

In [15]:
df["Delivery_person_Age"] = df["Delivery_person_Age"].replace("NaN ", np.nan)

In [16]:
df["Delivery_person_Age"] = pd.to_numeric(df["Delivery_person_Age"], errors="coerce")

In [17]:
df["Delivery_person_Ratings"] = df["Delivery_person_Ratings"].replace("NaN ", np.nan)

In [18]:
df["Delivery_person_Ratings"] = pd.to_numeric(
    df["Delivery_person_Ratings"],
    errors="coerce"
)

In [19]:
df["Time_taken(min)"] = df["Time_taken(min)"].str.replace(
    "(min) ",
    "",
    regex=False
)

In [20]:
df["Time_taken(min)"] = pd.to_numeric(
    df["Time_taken(min)"],
    errors="coerce"
)

In [21]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    format="%d-%m-%Y"
)

In [22]:
df["Time_Orderd"] = pd.to_datetime(
    df["Time_Orderd"],
    format="%H:%M:%S",
    errors="coerce"
)

In [23]:
df["Time_Order_picked"] = pd.to_datetime(
    df["Time_Order_picked"],
    format="%H:%M:%S",
    errors="coerce"
)

In [24]:
df.dtypes

ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                    datetime64[ns]
Time_Order_picked              datetime64[ns]
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                    object
Festival                               object
City                                   object
Time_taken(min)                         int64
dtype: object

In [25]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [26]:
df["Delivery_person_Ratings"].describe()

count    43685.000000
mean         4.633780
std          0.334716
min          1.000000
25%          4.500000
50%          4.700000
75%          4.900000
max          6.000000
Name: Delivery_person_Ratings, dtype: float64

In [27]:
df["Delivery_person_Ratings"].value_counts().sort_index()

Delivery_person_Ratings
1.0      38
2.5      20
2.6      22
2.7      22
2.8      19
2.9      19
3.0       6
3.1      29
3.2      29
3.3      25
3.4      32
3.5     249
3.6     207
3.7     225
3.8     228
3.9     197
4.0    1077
4.1    1430
4.2    1418
4.3    1409
4.4    1361
4.5    3303
4.6    6940
4.7    7142
4.8    7148
4.9    7041
5.0    3996
6.0      53
Name: count, dtype: int64

In [28]:
df["Delivery_person_Age"].describe()

count    43739.000000
mean        29.567137
std          5.815155
min         15.000000
25%         25.000000
50%         30.000000
75%         35.000000
max         50.000000
Name: Delivery_person_Age, dtype: float64

In [29]:
df["Delivery_person_Age"].value_counts().sort_index()

Delivery_person_Age
15.0      38
20.0    2136
21.0    2153
22.0    2196
23.0    2087
24.0    2210
25.0    2174
26.0    2159
27.0    2150
28.0    2179
29.0    2191
30.0    2226
31.0    2120
32.0    2202
33.0    2187
34.0    2166
35.0    2262
36.0    2260
37.0    2227
38.0    2219
39.0    2144
50.0      53
Name: count, dtype: int64

In [30]:
df["Time_taken(min)"].describe()

count    45593.000000
mean        26.294607
std          9.383806
min         10.000000
25%         19.000000
50%         26.000000
75%         32.000000
max         54.000000
Name: Time_taken(min), dtype: float64

In [31]:
df[df["Delivery_person_Ratings"] > 5]["Delivery_person_Ratings"].value_counts()2

Delivery_person_Ratings
6.0    53
Name: count, dtype: int64

In [32]:
df[df["Delivery_person_Ratings"] < 1]["Delivery_person_Ratings"].value_counts()

Series([], Name: count, dtype: int64)

In [33]:
df["Delivery_person_Age"].value_counts().sort_index()

Delivery_person_Age
15.0      38
20.0    2136
21.0    2153
22.0    2196
23.0    2087
24.0    2210
25.0    2174
26.0    2159
27.0    2150
28.0    2179
29.0    2191
30.0    2226
31.0    2120
32.0    2202
33.0    2187
34.0    2166
35.0    2262
36.0    2260
37.0    2227
38.0    2219
39.0    2144
50.0      53
Name: count, dtype: int64

In [34]:
df[df["Delivery_person_Age"] == 15]

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
2387,0x564,JAPRES15DEL03,15.0,1.0,-26.891191,75.802083,26.981191,75.892083,2022-03-12,NaT,1900-01-01 17:20:00,conditions NaN,NaN,3,Meal,motorcycle,0,No,Urban,15
2905,0xcd0,INDORES010DEL03,15.0,1.0,22.750040,75.902847,22.810040,75.962847,2022-04-03,NaT,1900-01-01 20:30:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,29
2951,0x91a,SURRES17DEL03,15.0,1.0,21.149569,72.772697,21.209569,72.832697,2022-03-21,NaT,1900-01-01 22:10:00,conditions NaN,NaN,3,Buffet,bicycle,1,No,Metropolitian,20
5902,0x474,CHENRES15DEL03,15.0,1.0,13.026286,80.275235,13.056286,80.305235,2022-03-11,NaT,1900-01-01 20:50:00,conditions NaN,NaN,3,Drinks,bicycle,1,No,Metropolitian,25
9156,0x73f,BANGRES05DEL01,15.0,1.0,12.970324,77.645748,13.080324,77.755748,2022-03-25,NaT,1900-01-01 23:25:00,conditions NaN,NaN,3,Buffet,motorcycle,2,No,Metropolitian,34
10900,0x1b49,MUMRES14DEL02,15.0,1.0,19.181300,72.836191,19.231300,72.886191,2022-03-30,NaT,1900-01-01 20:55:00,conditions NaN,NaN,3,Buffet,motorcycle,1,No,Metropolitian,39
11125,0x40b,SURRES12DEL01,15.0,1.0,-21.183434,-72.814492,21.193434,72.824492,2022-03-05,NaT,1900-01-01 11:30:00,conditions NaN,NaN,3,Meal,scooter,1,No,Urban,27
12093,0x523,INDORES03DEL02,15.0,1.0,22.751857,75.866699,22.801857,75.916699,2022-03-24,NaT,1900-01-01 21:15:00,conditions NaN,NaN,3,Buffet,bicycle,0,No,Metropolitian,28
15124,0x18b0,RANCHIRES02DEL01,15.0,1.0,0.000000,0.000000,0.070000,0.070000,2022-03-16,NaT,1900-01-01 23:55:00,conditions NaN,NaN,3,Meal,bicycle,1,No,Metropolitian,21
15927,0x550,CHENRES08DEL02,15.0,1.0,13.022394,80.242439,13.072394,80.292439,2022-03-11,NaT,1900-01-01 18:10:00,conditions NaN,NaN,3,Snack,bicycle,0,No,Metropolitian,17
16084,0x58c,MUMRES02DEL01,15.0,1.0,-19.221315,72.862381,19.231315,72.872381,2022-03-30,NaT,1900-01-01 12:05:00,conditions NaN,NaN,3,Snack,scooter,0,No,Metropolitian,23
16462,0xe4c,MYSRES05DEL03,15.0,1.0,12.323978,76.627961,12.413978,76.717961,2022-03-27,NaT,1900-01-01 20:00:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Urban,24
21222,0x3fc,BANGRES16DEL02,15.0,1.0,13.029198,77.570997,13.159198,77.700997,2022-03-06,NaT,1900-01-01 17:15:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,28
22291,0x3ed,RANCHIRES09DEL01,15.0,1.0,-23.351058,-85.325731,23.421058,85.395731,2022-03-27,NaT,1900-01-01 21:35:00,conditions NaN,NaN,3,Buffet,electric_scooter,2,Yes,Metropolitian,44
23035,0x415,VADRES17DEL01,15.0,1.0,0.000000,0.000000,0.070000,0.070000,2022-03-29,NaT,1900-01-01 00:00:00,conditions NaN,NaN,3,Snack,scooter,0,No,Urban,27
23488,0x616c,SURRES07DEL02,15.0,1.0,21.170798,72.790489,21.220798,72.840489,2022-03-24,NaT,1900-01-01 17:30:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,32
23644,0x1ea0,BANGRES17DEL02,15.0,1.0,12.972532,77.608179,13.022532,77.658179,2022-03-21,NaT,1900-01-01 17:40:00,conditions NaN,NaN,3,Drinks,bicycle,1,No,Metropolitian,23
23664,0x3f7,CHENRES04DEL01,15.0,1.0,-13.029780,-80.208812,13.139780,80.318812,2022-03-31,NaT,1900-01-01 22:40:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Urban,15
25873,0xbb3,CHENRES15DEL03,15.0,1.0,13.026286,80.275235,13.116286,80.365235,2022-03-20,NaT,1900-01-01 22:50:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,27
26633,0x730,INDORES15DEL02,15.0,1.0,22.760072,75.892574,22.840072,75.972574,2022-03-12,NaT,1900-01-01 17:35:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Metropolitian,27
26917,0x6e0,CHENRES06DEL03,15.0,1.0,13.054347,80.257221,13.114347,80.317221,2022-03-01,NaT,1900-01-01 18:20:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Urban,21
27118,0x3f2,BANGRES02DEL02,15.0,1.0,12.970221,77.645396,13.050221,77.725396,2022-03-02,NaT,1900-01-01 21:45:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Urban,20
27942,0x681,CHENRES07DEL03,15.0,1.0,13.081878,80.248519,13.111878,80.278519,2022-04-03,NaT,1900-01-01 21:50:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Metropolitian,27
28003,0x406,PUNERES14DEL01,15.0,1.0,18.516216,73.842527,18.586216,73.912527,2022-03-27,NaT,1900-01-01 19:30:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,38
29664,0x137e,MYSRES19DEL02,15.0,1.0,12.334022,76.618203,12.354022,76.638203,2022-03-01,NaT,1900-01-01 09:35:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,13
31216,0x32aa,JAPRES11DEL01,15.0,1.0,26.902940,75.793007,26.912940,75.803007,2022-03-09,NaT,1900-01-01 10:05:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Urban,19
31959,0x4240,PUNERES05DEL02,15.0,1.0,18.543626,73.905101,18.623626,73.985101,2022-03-08,NaT,1900-01-01 21:25:00,conditions NaN,NaN,3,Meal,bicycle,0,No,Metropolitian,21
33198,0x622,CHENRES03DEL02,15.0,1.0,-13.091809,80.219104,13.111809,80.239104,2022-03-03,NaT,1900-01-01 11:50:00,conditions NaN,NaN,3,Buffet,scooter,0,No,Metropolitian,33
34953,0x85c,COIMBRES17DEL02,15.0,1.0,11.026117,76.944652,11.046117,76.964652,2022-03-09,NaT,1900-01-01 09:10:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,19
36021,0xdc0,COIMBRES03DEL03,15.0,1.0,11.025083,77.015393,11.085083,77.075393,2022-03-03,NaT,1900-01-01 18:55:00,conditions NaN,NaN,3,Meal,motorcycle,1,No,Metropolitian,28
37100,0x451,HYDRES14DEL03,15.0,1.0,-17.426228,-78.407495,17.486228,78.467495,2022-03-19,NaT,1900-01-01 19:05:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Urban,30
37676,0x424,PUNERES20DEL02,15.0,1.0,-18.592718,-73.773572,18.672718,73.853572,2022-03-16,NaT,1900-01-01 20:25:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Urban,30
39073,0x4a6,COIMBRES07DEL02,15.0,1.0,-10.961850,-76.971082,11.091850,77.101082,2022-03-02,NaT,1900-01-01 19:55:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,24
39082,0x1144,MYSRES05DEL01,15.0,1.0,12.323978,76.627961,12.433978,76.737961,2022-03-29,NaT,1900-01-01 22:10:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Metropolitian,30
40285,0x442,CHENRES16DEL02,15.0,1.0,-13.049645,-80.242268,13.129645,80.322268,2022-03-08,NaT,1900-01-01 23:05:00,conditions NaN,NaN,3,Snack,bicycle,0,No,Metropolitian,25
41241,0x49c,COIMBRES14DEL02,15.0,1.0,11.003681,76.975525,11.133681,77.105525,2022-04-02,NaT,1900-01-01 23:45:00,conditions NaN,NaN,3,Meal,scooter,0,No,Metropolitian,25
44403,0x2314,VADRES04DEL01,15.0,1.0,0.000000,0.000000,0.070000,0.070000,2022-03-14,NaT,1900-01-01 17:40:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,34
44881,0x8d4,CHENRES02DEL02,15.0,1.0,13.086438,80.220672,13.216439,80.350672,2022-03-18,NaT,1900-01-01 18:00:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Urban,26

In [35]:
df[df["Time_Orderd"].isna()].head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
42,0x4f0,MUMRES17DEL02,NaN,NaN,19.121999,72.908493,19.201999,72.988493,2022-04-06,NaT,1900-01-01 18:35:00,conditions Cloudy,Medium,1,Drinks,scooter,1,No,Metropolitian,33
74,0xa9f,BANGRES13DEL01,NaN,NaN,12.935662,77.614130,12.975662,77.654130,2022-03-11,NaT,1900-01-01 15:30:00,conditions NaN,NaN,1,Drinks,scooter,0,No,Metropolitian,19
120,0x6e2,VADRES06DEL01,NaN,NaN,22.312790,73.170283,22.422790,73.280283,2022-04-02,NaT,1900-01-01 18:25:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Metropolitian,25
140,0x1ec7,PUNERES05DEL03,NaN,NaN,18.543626,73.905101,18.573626,73.935101,2022-03-09,NaT,1900-01-01 23:40:00,conditions Stormy,Low,2,Snack,scooter,0,No,NaN,19
179,0x1b58,JAPRES03DEL01,NaN,NaN,26.913483,75.803139,26.983483,75.873139,2022-03-12,NaT,1900-01-01 17:50:00,conditions Sandstorms,Medium,0,Drinks,motorcycle,0,No,Metropolitian,43

In [36]:
# Handle invalid values identified during data validation

# Delivery ratings: 6 is outside the expected rating range
df.loc[df["Delivery_person_Ratings"] == 6, "Delivery_person_Ratings"] = np.nan

# Delivery partner age: 15 is considered an invalid value
df.loc[df["Delivery_person_Age"] == 15, "Delivery_person_Age"] = np.nan

In [37]:
print("Ratings > 5:", (df["Delivery_person_Ratings"] > 5).sum())
print("Age < 18:", (df["Delivery_person_Age"] < 18).sum())

Ratings > 5: 0
Age < 18: 0

In [38]:
categorical_columns = [
    "Weatherconditions",
    "Road_traffic_density",
    "Vehicle_condition",
    "Type_of_order",
    "Type_of_vehicle",
    "multiple_deliveries",
    "Festival",
    "City"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Weatherconditions ---
Weatherconditions
conditions Fog           7654
conditions Stormy        7586
conditions Cloudy        7536
conditions Sandstorms    7495
conditions Windy         7422
conditions Sunny         7284
conditions NaN            616
Name: count, dtype: int64

--- Road_traffic_density ---
Road_traffic_density
Low        15477
Jam        14143
Medium     10947
High        4425
NaN          601
Name: count, dtype: int64

--- Vehicle_condition ---
Vehicle_condition
2    15034
1    15030
0    15009
3      520
Name: count, dtype: int64

--- Type_of_order ---
Type_of_order
Snack      11533
Meal       11458
Drinks     11322
Buffet     11280
Name: count, dtype: int64

--- Type_of_vehicle ---
Type_of_vehicle
motorcycle           26435
scooter              15276
electric_scooter      3814
bicycle                 68
Name: count, dtype: int64

--- multiple_deliveries ---
multiple_deliveries
1       28159
0       14095
2        1985
NaN       993
3         361
Name: count, dtype: int64

--- Festival ---
Festival
No      44469
Yes       896
NaN       228
Name: count, dtype: int64

--- City ---
City
Metropolitian     34093
Urban             10136
NaN                1200
Semi-Urban          164
Name: count, dtype: int64

In [39]:
df["Weatherconditions"] = df["Weatherconditions"].replace(
    "conditions NaN", np.nan
)

In [43]:
df["Weatherconditions"].value_counts(dropna=False)

Weatherconditions
conditions Fog           7654
conditions Stormy        7586
conditions Cloudy        7536
conditions Sandstorms    7495
conditions Windy         7422
conditions Sunny         7284
NaN                       616
Name: count, dtype: int64

In [41]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing_Count"] > 0
].sort_values("Missing_Count", ascending=False)

missing_summary

                         Missing_Count  Missing_Percentage
Delivery_person_Ratings           1961                4.30
Delivery_person_Age               1892                4.15
Time_Orderd                       1731                3.80
Weatherconditions                  616                1.35

## Missing Value Treatment

After converting placeholder values such as `"NaN "` into actual missing values, four columns contain missing data.

| Column | Missing % | Treatment |
|---|---:|---|
| Delivery_person_Ratings | 4.30% | Kept as NaN |
| Delivery_person_Age | 4.15% | Kept as NaN |
| Time_Orderd | 3.80% | Kept as NaT |
| Weatherconditions | 1.35% | Kept as NaN |

Missing values were not replaced with arbitrary values such as 0 because doing so could distort the analysis. Rows will only be excluded from specific analyses when the required variable is missing.

In [44]:
numeric_columns = [
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude",
    "Vehicle_condition",
    "Time_taken(min)"
]

for col in numeric_columns:
    print(f"\n--- {col} ---")
    print(df[col].describe())

--- Restaurant_latitude ---
count    45593.000000
mean        17.017729
std          8.185109
min        -30.905562
25%         12.933284
50%         18.546947
75%         22.728163
max         30.914057
Name: Restaurant_latitude, dtype: float64

--- Restaurant_longitude ---
count    45593.000000
mean        70.231332
std         22.883647
min        -88.366217
25%         73.170000
50%         75.898497
75%         78.044095
max         88.433452
Name: Restaurant_longitude, dtype: float64

--- Delivery_location_latitude ---
count    45593.000000
mean        17.465186
std          7.335122
min          0.010000
25%         12.988453
50%         18.633934
75%         22.785049
max         31.054057
Name: Delivery_location_latitude, dtype: float64

--- Delivery_location_longitude ---
count    45593.000000
mean        70.845702
std         21.118812
min          0.010000
25%         73.280000
50%         76.002574
75%         78.107044
max         88.563452
Name: Delivery_location_longitude, dtype: float64

--- Vehicle_condition ---
count    45593.000000
mean         1.023359
std          0.839065
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          3.000000
Name: Vehicle_condition, dtype: float64

--- Time_taken(min) ---
count    45593.000000
mean        26.294607
std          9.383806
min         10.000000
25%         19.000000
50%         26.000000
75%         32.000000
max         54.000000
Name: Time_taken(min), dtype: float64

In [45]:
print("Vehicle condition:")
print(sorted(df["Vehicle_condition"].unique()))

print("\nMultiple deliveries:")
print(df["multiple_deliveries"].value_counts(dropna=False).sort_index())

print("\nDelivery time:")
print(sorted(df["Time_taken(min)"].unique()))

Vehicle condition:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3)]

Multiple deliveries:
multiple_deliveries
0       14095
1       28159
2        1985
3         361
NaN       993
Name: count, dtype: int64

Delivery time:
[np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54)]

In [46]:
zero_coordinate_counts = {
    "Restaurant_latitude_0": (df["Restaurant_latitude"] == 0).sum(),
    "Restaurant_longitude_0": (df["Restaurant_longitude"] == 0).sum(),
    "Delivery_latitude_0": (df["Delivery_location_latitude"] == 0).sum(),
    "Delivery_longitude_0": (df["Delivery_location_longitude"] == 0).sum()
}

zero_coordinate_counts

{'Restaurant_latitude_0': np.int64(3640),
 'Restaurant_longitude_0': np.int64(3640),
 'Delivery_latitude_0': np.int64(0),
 'Delivery_longitude_0': np.int64(0)}

In [47]:
zero_coordinate_rows = df[
    (df["Restaurant_latitude"] == 0) |
    (df["Restaurant_longitude"] == 0) |
    (df["Delivery_location_latitude"] == 0) |
    (df["Delivery_location_longitude"] == 0)
]

zero_coordinate_rows.shape

(3640, 20)

In [48]:
zero_coordinate_rows[[
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude",
    "City",
    "Time_taken(min)"
]].head(10)

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,City,Time_taken(min)
33,0.0,0.0,0.11,0.11,Urban,35
52,0.0,0.0,0.03,0.03,Metropolitian,15
57,0.0,0.0,0.08,0.08,Semi-Urban,49
59,0.0,0.0,0.06,0.06,Metropolitian,30
67,0.0,0.0,0.02,0.02,Metropolitian,15
68,0.0,0.0,0.04,0.04,Urban,16
72,0.0,0.0,0.08,0.08,Urban,15
73,0.0,0.0,0.02,0.02,Metropolitian,17
76,0.0,0.0,0.05,0.05,Metropolitian,27
81,0.0,0.0,0.11,0.11,Metropolitian,25

In [49]:
df[[
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude"
]].describe()

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude
count,45593.000000,45593.000000,45593.000000,45593.000000
mean,17.017729,70.231332,17.465186,70.845702
std,8.185109,22.883647,7.335122,21.118812
min,-30.905562,-88.366217,0.010000,0.010000
25%,12.933284,73.170000,12.988453,73.280000
50%,18.546947,75.898497,18.633934,76.002574
75%,22.728163,78.044095,22.785049,78.107044
max,30.914057,88.433452,31.054057,88.563452

In [50]:
df[
    (df["Delivery_location_latitude"] < 1) |
    (df["Delivery_location_longitude"] < 1)
][[
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude",
    "City",
    "Time_taken(min)"
]].head(20)

,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,City,Time_taken(min)
33,0.0,0.0,0.11,0.11,Urban,35
52,0.0,0.0,0.03,0.03,Metropolitian,15
57,0.0,0.0,0.08,0.08,Semi-Urban,49
59,0.0,0.0,0.06,0.06,Metropolitian,30
67,0.0,0.0,0.02,0.02,Metropolitian,15
68,0.0,0.0,0.04,0.04,Urban,16
72,0.0,0.0,0.08,0.08,Urban,15
73,0.0,0.0,0.02,0.02,Metropolitian,17
76,0.0,0.0,0.05,0.05,Metropolitian,27
81,0.0,0.0,0.11,0.11,Metropolitian,25
136,0.0,0.0,0.04,0.04,Urban,17
147,0.0,0.0,0.04,0.04,Urban,26
149,0.0,0.0,0.04,0.04,Urban,41
152,0.0,0.0,0.02,0.02,Metropolitian,19
153,0.0,0.0,0.01,0.01,Metropolitian,27
164,0.0,0.0,0.07,0.07,Metropolitian,43
172,0.0,0.0,0.06,0.06,Urban,19
216,0.0,0.0,0.06,0.06,Metropolitian,28
223,0.0,0.0,0.13,0.13,Metropolitian,39
229,0.0,0.0,0.03,0.03,Metropolitian,25

In [51]:
invalid_coordinates = (
    (df["Restaurant_latitude"] == 0) &
    (df["Restaurant_longitude"] == 0)
)

df.loc[invalid_coordinates, [
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude"
]] = np.nan

In [52]:
df[[
    "Restaurant_latitude",
    "Restaurant_longitude",
    "Delivery_location_latitude",
    "Delivery_location_longitude"
]].isna().sum()

Restaurant_latitude            3640
Restaurant_longitude           3640
Delivery_location_latitude     3640
Delivery_location_longitude    3640
dtype: int64

In [53]:
print("Shape:", df.shape)
print("\nDuplicate rows:", df.duplicated().sum())
print("\nMissing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

Shape: (45593, 20)

Duplicate rows: 0

Missing values:
Delivery_person_Age            1892
Delivery_person_Ratings        1961
Restaurant_latitude            3640
Restaurant_longitude           3640
Delivery_location_latitude     3640
Delivery_location_longitude    3640
Time_Orderd                    1731
Weatherconditions               616
dtype: int64

In [54]:
df.to_csv("../data/cleaned/food_delivery_cleaned.csv", index=False)

In [55]:
import os

os.path.exists("../data/cleaned/food_delivery_cleaned.csv")

True

## Data Cleaning Summary

The dataset was cleaned using a reproducible process while preserving the original raw data.

### Cleaning actions performed

- Converted placeholder `"NaN "` values into proper missing values.
- Converted numeric columns such as delivery partner age and ratings to numeric data types.
- Removed the `"(min) "` text from `Time_taken(min)` and converted it to integer.
- Converted `Order_Date` to datetime.
- Converted `Time_Orderd` and `Time_Order_picked` to time-based datetime values.
- Identified and handled invalid delivery partner ratings above the expected range.
- Identified and handled invalid delivery partner ages below the expected working-age threshold.
- Converted invalid restaurant coordinates represented by `(0, 0)` to missing values.
- Preserved rows with missing values instead of deleting them unnecessarily.
- Verified that the dataset contains no duplicate rows.
- Confirmed that the target variable `Time_taken(min)` contains no missing values.

### Final Dataset

- Rows: 45,593
- Columns: 20
- Duplicate rows: 0
- Target missing values: 0

The cleaned dataset was saved as `food_delivery_cleaned.csv`.

Earliest order date: 2022-02-11 00:00:00
Latest order date: 2022-04-06 00:00:00